### ISSUE TITLE
build failure with PG12: hypopg.c:56:10: fatal error: optimizer/var.h: No such file or directory

### ISSUE THREAD

**Issue by df7cb** [HypoPG/hypopg#39]
Trying to build against 12beta1:

```
15:30:55 gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -I./ -I/usr/include/postgresql/12/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o hypopg.o hypopg.c
15:30:55 hypopg.c:56:10: fatal error: optimizer/var.h: No such file or directory
15:30:55  #include "optimizer/var.h"
15:30:55           ^~~~~~~~~~~~~~~~~
15:30:55 compilation terminated.
```

**Comment by rjuju** [comment]
That's annoying, as current HEAD is currently in beta for v2.0.0, with at least one pending issue (for runtime partition pruning) :(

I'm wondering if I should try to maintain a v1 branch, with at least a fix for that so we can provide a stable version of hypopg for pg12.  Would that work for debian packages?

**Comment by df7cb** [comment]
Sure, if you attach a git branch at the correct point, we could build packages from there. (Plus a tag to create a release tarball.)

**Comment by rjuju** [comment]
Ok, thanks for confirming!  I'll add such a branch shortly after pgCon.

**Comment by rjuju** [comment]
I just pushed the REL1_BRANCH, which backports all hypothetical indexes changes from master and also fixes pg12 compatibility.  Regression tests works from 9.2 up to 12, so everything should be ok.

I'm not sure of if other things should be change in debian/ though, so I didn't push any tag yet.

**Comment by df7cb** [comment]
Re: Julien Rouhaud 2019-06-16 <HypoPG/hypopg/issues/39/502437287@github.com>
> I just pushed the REL1_BRANCH, which backports all hypothetical indexes changes from master and also fixes pg12 compatibility.  Regression tests works from 9.2 up to 12, so everything should be ok.

Looks good indeed, thanks!

> I'm not sure of if other things should be change in debian/ though, so I didn't push any tag yet.

The date in debian/changelog is broken, it needs to be `Jun`. (That's
the format also used by `date -R`, and 822-email.)

(I can't push or else I would have fixed that part.)

Christoph

**Comment by rjuju** [comment]
Oops, sorry for that.  I just fixed it.

**Comment by df7cb** [comment]
Almost:
```
W: postgresql-11-hypopg: debian-changelog-has-wrong-day-of-week 2019-06-16 is a Sunday
```
... sorry for not spotting that. (It's no longer an error, just a warning...)

Could you also tag a release?

**Comment by rjuju** [comment]
That's quite embarassing :)  I checked with `date -R -d "2019-06-16"`  so it shouldn't be any other silly mistake.  Pushed with the tag 1.1.3!

**Comment by df7cb** [comment]
Successfully built new packages now. Thanks!

**Comment by rjuju** [comment]
\o/ thanks a lot!
