### ISSUE TITLE
Postgres 12

### ISSUE THREAD

**Issue by ankane** [HypoPG/hypopg#41]
Hi, thanks for this awesome project 👍 

When running `make` on the master branch against Postgres 12 (on Debian 10), it's erroring with:

```text
hypopg_index.c:47:10: fatal error: nodes/relation.h: No such file or directory
 #include "nodes/relation.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: hypopg_index.o] Error 1
```

**Comment by rjuju** [comment]
Hello,

Thanks a lot!

Yes, unfortunately the master branch is still being developed as pg12 changed quite a lot of thing wrt. partitioning.

I maintain a v1 (with only hypothetical indexes) on the branch REL1_STABLE, which should work just fine (it's being used for at least debian packages).

**Comment by ankane** [comment]
Thanks for the super fast response @rjuju. I missed the 1.1.3 release (which seems to be aligned with `REL1_STABLE`). Just tried it out and it's working great - my bad!

**Comment by rjuju** [comment]
Great!
