### ISSUE TITLE
Could not load library on postgresql 12 

### ISSUE THREAD

**Issue by konstantin-kostadinov** [HypoPG/hypopg#43]
After pg_upgrade from v11 to v12 I'm getting this error when craeting the extension.
`ERROR:  could not load library "/usr/lib/postgresql/12/lib/hypopg.so": /usr/lib/postgresql/12/lib/hypopg.so: undefined symbol: AllocSetContextCreateExtended`

**Comment by rjuju** [comment]
Hello,

hypopg is calling AllocSetContextCreate(): https://github.com/HypoPG/hypopg/blob/REL1_STABLE/hypopg.c#L94

This is a macro calling AllocSetContextCreateExtended in pg11:

```
#if defined(HAVE__BUILTIN_CONSTANT_P) && defined(HAVE__VA_ARGS)
#define AllocSetContextCreate(parent, name, ...) \
	(StaticAssertExpr(__builtin_constant_p(name), \
					  "memory context names must be constant strings"), \
	 AllocSetContextCreateExtended(parent, name, __VA_ARGS__))
#else
#define AllocSetContextCreate \
	AllocSetContextCreateExtended
#endif
```

but not anymore in pg12:

```
#ifdef HAVE__BUILTIN_CONSTANT_P
#define AllocSetContextCreate(parent, name, ...) \
	(StaticAssertExpr(__builtin_constant_p(name), \
					  "memory context names must be constant strings"), \
	 AllocSetContextCreateInternal(parent, name, __VA_ARGS__))
#else
#define AllocSetContextCreate \
	AllocSetContextCreateInternal
#endif
```

This was changed in https://github.com/postgres/postgres/commit/13cd7209f79.

It seems that this version you're using was compiled against pg11, or an older version of pg12.  How did you install it?

**Comment by konstantin-kostadinov** [comment]
I upgraded using pg_upgradecluster.
You are right. After recompiling hypopg the error disappeared.
Thank you!

**Comment by rjuju** [comment]
Good news!
