### ISSUE TITLE
pg 12 support already work in progress?

### ISSUE THREAD

**Issue by darix** [HypoPG/hypopg#44]

**Comment by rjuju** [comment]
Hello,

hypopg is already compatible with pg12.  You just need to use the REL1_STABLE branch, which is already used for packages.

**Comment by darix** [comment]
ah I tried master and there I saw issue. switching my package to the branch.

**Comment by darix** [comment]
[openSUSE package now available here](https://build.opensuse.org/package/show/server:database:postgresql/hypopg)

**Comment by rjuju** [comment]
Oh, great, thank you very much!
