### ISSUE TITLE
Not working for Postgres 12 on windows

### ISSUE THREAD

**Issue by anupkumarmishra** [HypoPG/hypopg#50]
Any plan to support on Postgres 12 , Windows version . I have tried doing it myself but facing a lot of issues.

**Comment by rjuju** [comment]
As far as I know the code should be compatible with windows.  I don't use windows so I can't try to compile it, but if you do and face compilation errors please report them here so I can try to fix the code.  Unfortunately without that there isn't much I can do to help.

**Comment by anupkumarmishra** [comment]
![Capture](https://user-images.githubusercontent.com/2819529/81173282-70116300-8fbd-11ea-9f4e-096919caf22f.JPG)

Please find attached the screenshot . I have followed everything as given here :
1)http://www.programmersought.com/article/896664505/
2)https://www.2ndquadrant.com/en/blog/compiling-postgresql-extensions-visual-studio-windows/

I have given postgres.lib in linker dependencies as mentioned in these blogs.  Please guide what maybe wrong.

Also in the source file i have just added hypopg.c and rest of the files are in the same directory as these files.

**Comment by rjuju** [comment]
Well, it seems to me that it's an environment issue, not a hypopg issue.  Can you successfully compile other custom extensions or do you always get the same problem?  Unless that's specific to hypopg there's nothing I can do in hypopg to help.

**Comment by anupkumarmishra** [comment]
I did compile the extension pg_qualstats yesterday successfully .

**Comment by rjuju** [comment]
I see.  I'm assuming that you used the exact same settings for both, and double checked?

Which version of postgres are you compiling against, which version/git commit of pg_qualstats successfully compiled and which version/git commit hypopg is failing?

I don't see any difference really relevant in both extensions, and the error isn't particularly helpful either.

**Comment by anupkumarmishra** [comment]
Yes , same setting for both . I am compiling against Postgres 12 and version of pg_qualstats is 2.0.1 and hypopg 1.1.2. Thanks !

**Comment by rjuju** [comment]
Oh, could you try with hypopg 1.1.3?  You're missing a bunch of fixes, including windows fixes and pg12 compatibility, so it's clear that it won't work (see the changes between 1.1.2 and 1.1.3 at https://github.com/HypoPG/hypopg/compare/1.1.2...1.1.3).

**Comment by rjuju** [comment]
Without news for the last few months, I'm closing this issue.
