### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by Extortioner01** [HypoPG/hypopg#51]
Hello! Thank you for your extension! 
I found some problems with it:

In DOCS you created column "line" in example (CREATE TABLE hypo (id integer, line text) ;), but after you tried to select column "val" (EXPLAIN SELECT val FROM hypo WHERE id = 1;)

And second problem with functions:
\df 
 Schema |         Name         | Result data type |                                                           
--------+----------------------+------------------+-----------------------------------------------------------
 public | hypopg               | SETOF record     | OUT indexname text, OUT indexrelid oid, OUT indrelid oid, 
 public | hypopg_create_index  | SETOF record     | sql_order text, OUT indexrelid oid, OUT indexname text    
 public | hypopg_drop_index    | boolean          | indexid oid                                               
 public | hypopg_get_indexdef  | text             | indexid oid                                               
 public | hypopg_list_indexes  | SETOF record     | OUT indexrelid oid, OUT indexname text, OUT nspname name, 
 public | hypopg_relation_size | bigint           | indexid oid                                               
 public | hypopg_reset         | void             |                                                           
 public | hypopg_reset_index   | void             |                                                           
(8 rows)

I got error when i try to do something like that:
SELECT hypopg_partition_table('hypo_part_range', 'PARTITION BY RANGE(id)');

select * from pg_available_extensions where name = 'hypopg' \gx
-[ RECORD 1 ]-----+------------------------------------
name              | hypopg
default_version   | 1.1.3
installed_version | 1.1.3
comment           | Hypothetical indexes for PostgreSQL

PostgreSQL 11.7

**Comment by rjuju** [comment]
Thanks for the report!  I fixed the documentation issue in d63c0634b88bd1ae2e03e96f7ed878b4cc26653b.

For your second issue, hypothetical table partitioning is something that's planned with version 2 of hypopg.  Unfortunately, postgres 12 did a lot of changes in how partitioning is handled, and for now we didn't find a way to make hypothetical partitioning work with this version, which is why v2 is not released.
