### ISSUE TITLE
ALTER EXTENSION fails

### ISSUE THREAD

**Issue by Krysztophe** [HypoPG/hypopg#54]
There are no such scripts as ''hypopg--1.1.3-1.1.4.sql'', so an ALTER UPDATE  fails:
```
powa=# ALTER EXTENSION hypopg UPDATE;
ERROR: extension "hypopg" has no update path from version "1.1.3" to version "1.1.4"
```
The  extension can be dropped and reinstalled, but this is disturbing for a user.

Are dummy scripts an option in the future?

**Comment by rjuju** [comment]
Hello,

This is intended.  As hypopg doesn't create any table and doesn't store any data outside a transaction's local memory, there's no need to create upgrade scripts.  You can simply drop and create the extension to get the new versions.

> Are dummy scripts an option in the future?

I'm afraid no, as it'll double the work required for the SQL wrappers, on top of adding possibility of forgetting something in one of the scripts.  For the record, there are third-party extensions (e.g. plpgslq_check) that have the same approach so it shouldn't be so surprising for users.  I can add some documentation to point out that an upgrade is actually a drop/create.

**Comment by Krysztophe** [comment]
OK, we can live with that.

Yes, a bit of documentation would be nice.

**Comment by rjuju** [comment]
Done in https://github.com/HypoPG/hypopg/commit/82900d1cafc4a466e4b2bc715c1d24b22795a6b9!

**Comment by rjuju** [comment]
@Krysztophe now that I have a tool to validate extension upgrade scripts, I'm willing to reconsider this for both this extension and pg_qualstat!

I'll keep this issue opened for now as a reminder to provide an upgrade script next time.

**Comment by rjuju** [comment]
I just pushed https://github.com/HypoPG/hypopg/commit/30c4f2a52c74da44f8ce1b28b764260c91cdb7ab to start working on 1.3.2, which includes an upgrade script!  I'm closing this issue as following version should follow the same pattern.
