### ISSUE TITLE
Index size estimations for small indexes seem inaccurate

### ISSUE THREAD

**Issue by Bensk1** [HypoPG/hypopg#55]
Hi again,

I am running some experiments with a TPC-DS data set with a scale factor of 10 in PostgreSQL 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1). For some small indexes, the estimated size does not change if I append attributes to a single attribute index, i.e., create a multi-attribute index. I am not sure if this is intended and a correct estimation or actually an issue.

```
SELECT * FROM hypopg_create_index('CREATE INDEX ON store (s_store_sk)');
SELECT * FROM hypopg_create_index('CREATE INDEX ON store (s_number_employees)');
SELECT * FROM hypopg_create_index('CREATE INDEX ON store (s_store_name)');

SELECT * FROM hypopg_create_index('CREATE INDEX ON store (s_store_sk, s_number_employees)');
SELECT * FROM hypopg_create_index('CREATE INDEX ON store (s_store_sk, s_number_employees, s_store_name)');

SELECT indexname, pg_size_pretty(hypopg_relation_size(indexrelid)) FROM hypopg_list_indexes();
                            indexname                            | pg_size_pretty
-----------------------------------------------------------------+----------------
 <84741773>btree_store_s_store_sk                                | 8192 bytes
 <84741774>btree_store_s_number_employees                        | 8192 bytes
 <84741777>btree_store_s_store_name                              | 8192 bytes
 <84741776>btree_store_s_store_sk_s_number_employees             | 8192 bytes
 <84741775>btree_store_s_store_sk_s_number_employees_s_store_nam | 8192 bytes
 ```

```
select attname, avg_width from pg_stats where tablename = 'store';
      attname       | avg_width
--------------------+-----------
 s_store_sk         |         4
 s_street_number    |         3
 s_street_name      |         9
 s_street_type      |        16
 s_suite_number     |        11
 s_city             |        10
 s_county           |        15
 s_state            |         3
 s_zip              |        11
 s_country          |        14
 s_gmt_offset       |         5
 s_tax_precentage   |         4
 s_hours            |        21
 s_store_id         |        17
 s_rec_start_date   |         4
 s_rec_end_date     |         4
 s_closed_date_sk   |         4
 s_store_name       |         4
 s_number_employees |         4
 s_floor_space      |         4
 s_division_name    |         8
 s_market_id        |         4
 s_geography_class  |         8
 s_company_id       |         4
 s_company_name     |         8
 s_market_desc      |        58
 s_market_manager   |        13
 s_manager          |        13
 s_division_id      |         4
(29 rows)
```

Thanks for your support!

**Comment by rjuju** [comment]
Hello!

Apparently the table is so small that no matter how many columns you use in the index, it never use more than 1 block (which is the smallest size for an index).

How many records are there in the `store` table?

Also, note that hypopg will use the current statistics to estimate the hypothetical index size, so doing an ANALYZE store (or any useful table) may change the estimates if the table was just loaded an no autovacuum ran since.

**Comment by Bensk1** [comment]
It is indeed a small table and has only 102 records and I did an `ANALYZE store` before I checked the size above. I guess it is just about the small size of the table and no issue. Thank you!

**Comment by rjuju** [comment]
Ah, then the result is definitely expected.  Using the biggest hypothetical index you tried (`CREATE INDEX ON store (s_store_sk, s_number_employees, s_store_name)`), here's an approximation of the hypothetical index size:

```
total attribute average width = 4 + 4 + 4 = 12B

per line size = total attribute average width
    + size of IndexTupleData * num cols
    + size of ItemIdData * num cols
( last two are internal structure stored in btree indexes)
= 12 + 3 * 8 + 3 * 4 = 48B

bloat =regular fill factor (90) + additional 20% bloat (to simulate index a bit bloated) = 1.3x growth

index size = 48 * 102 * 1.3 = 6364.8B
```

So even this one fits in a single block (even when removing the space used for per-block information).

For reference, you can see more details on this at https://github.com/HypoPG/hypopg/blob/REL1_STABLE/hypopg_index.c#L1734-L1742

```
		/* -------------------------------
		 * quick estimating of index size:
		 *
		 * sizeof(PageHeader) : 24 (1 per page)
		 * sizeof(BTPageOpaqueData): 16 (1 per page)
		 * sizeof(IndexTupleData): 8 (1 per tuple, referencing heap)
		 * sizeof(ItemIdData): 4 (1 per tuple, storing the index item)
		 * default fillfactor: 90%
		 * no NULL handling
		 * fixed additional bloat: 20%
```

There are clearly some caveats: NULL attributes extra size isn't accounted for, and non-leaf pages are also not accounted for, but it keeps the code simpler and should give a size of the same order of magnitude, which should be enough to know if postgres would use such an index or not.

**Comment by Bensk1** [comment]
Thanks a lot, that was quite helpful!
