### ISSUE TITLE
Regression tests are failing

### ISSUE THREAD

**Issue by devrimgunduz** [HypoPG/hypopg#58]
Hi,
Regression tests are failing on v14 and 13. I did not test other ones. Should be easy to fix. Can you please take a look? Logs are attached.

Regards, Devrim

[regression.diffs-hypopg-pg13.txt](https://github.com/HypoPG/hypopg/files/6592297/regression.diffs-hypopg-pg13.txt)
[regression.diffs-hypopg-pg14.txt](https://github.com/HypoPG/hypopg/files/6592298/regression.diffs-hypopg-pg14.txt)

**Comment by rjuju** [comment]
Thanks for the report @devrimgunduz !  I actually already fixed that a couple of months ago in 8eb71b0dda1ec4b8c42f7a15348ab7fcf8529f8a.

I'll release hypopg 1.3.0 tomorrow, after some more tests, as this version will now include support for hypothetical hash indexes.

**Comment by devrimgunduz** [comment]
Great, thanks!

**Comment by rjuju** [comment]
@devrimgunduz I just released version 1.3.0!  Let me know if there's any issue with it.

**Comment by devrimgunduz** [comment]
Thanks @rjuju ! It works great. Closing this issue.

**Comment by rjuju** [comment]
good news, thanks for the confirmation!
