### ISSUE TITLE
Cannot create extension in psql (Ubuntu)

### ISSUE THREAD

**Issue by minhduchoang301** [HypoPG/hypopg#61]
I use Ubuntu 20.04 (wsl2). I tried sudo make install and it ran perfectly. However, it fails with this error when I create extension: 

ERROR:  could not load library "/usr/lib/postgresql/13/lib/hypopg.so": /usr/lib/postgresql/13/lib/hypopg.so: undefined symbol: errstart_cold

**Comment by rjuju** [comment]
Hi,

errstart_cold was introduced in pg 14 and it looks like you're creating the extension on pg13.

Do you have pg14 (or more recent) installed?  One usual issue is getting a difffent pg_config when using sudo compared to the one on your current shell.

You should check that sudo pg_config returns the correct postgres version, if not fix it and do a full clean / make / make install cycle.

**Comment by minhduchoang301** [comment]
Thank you! problem solved
