### ISSUE TITLE
hypopg_list_indexes() does not work normally

### ISSUE THREAD

**Issue by minhduchoang301** [HypoPG/hypopg#62]
I follow the steps listed in the readme. Everything works fine, including other examples using hypopg's function with a command inside(). However, I have trouble with this command:

tpch=# SELECT * FROM hypopg_list_indexes();
ERROR:  function hypopg_list_indexes() does not exist
LINE 1: SELECT * FROM hypopg_list_indexes();
                      ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

**Comment by minhduchoang301** [comment]
when I visualize which functions are installed, only these are: 
 Schema |         Name         |  Owner   | Access privileges | Language |     Source code      | Description
--------+----------------------+----------+-------------------+----------+----------------------+-------------
 public | hypopg               | postgres |                   | c        | hypopg               |
 public | hypopg_create_index  | postgres |                   | c        | hypopg_create_index  |
 public | hypopg_drop_index    | postgres |                   | c        | hypopg_drop_index    |
 public | hypopg_get_indexdef  | postgres |                   | c        | hypopg_get_indexdef  |
 public | hypopg_relation_size | postgres |                   | c        | hypopg_relation_size |
 public | hypopg_reset         | postgres |                   | c        | hypopg_reset         |
 public | hypopg_reset_index   | postgres |                   | c        | hypopg_reset_index   |
(7 rows)

**Comment by rjuju** [comment]
Hi,

Indeed a recent commit changed `hypopg_list_indexes` from a function to a view, so it's easier to use (mostly because you can rely on psql's autocompletion), and forgot to update the documentation.

Thanks for the report, this is now fixed: https://github.com/HypoPG/hypopg/commit/6e2d7bfca12e1aeb58bd77d96b9c222b759df33d
