### ISSUE TITLE
Not working for Pg14

### ISSUE THREAD

**Issue by payne911** [HypoPG/hypopg#63]
I recently ran `brew upgrade` which updated postgres to version 14.

Now when I run `CREATE EXTENSION hypopg;` I get:

```
ERROR:  incompatible library "/usr/local/lib/postgresql/hypopg.so": version mismatch
DETAIL:  Server is version 14, library is version 13.
SQL state: XX000
```

**Comment by rjuju** [comment]
Hi,

I don't know how brew is handling postgres, but it looks like it's using a --prefix option that doesn't contain the major postgres version which lead to starting postgres 14 binaries using libraries compiled for postgres 13.  Or is this `/usr/local/lib/postgresql/` a path you configured yourself?

I can't say if it's a missing dependency from brew or not as I don't know if hypopg is packaged by brew, but you should be able to fix that problem by either forcing an upgrade of hypopg via brew, or doing a full compilation cycle if using from source (something like `make -s clean && make -s install`).

Ideally you should also put the major version in all the postgres patch, but if that comes from brew you may not have that option.

**Comment by payne911** [comment]
I didn't configure anything myself, and am quite new to the whole MacOS thing.

`make -s clean && make -s install` gives me this:

![image](https://user-images.githubusercontent.com/38117856/145440327-8f270626-9912-4345-bab1-5108e94700e0.png)

**Comment by rjuju** [comment]
How did you install hypopg for postgres 13?

**Comment by payne911** [comment]
`git clone` this current repo, and use `make` to install it.

**Comment by rjuju** [comment]
I don't understand how you could compile it if you miss the sysroot and some header.

You need to compile and install it again after changing the major postgres versions, so following the same steps may work.  You don't need to clone the repository again though, only clean the compiled file as in make clean.

**Comment by payne911** [comment]
Ah, I was talking about when I installed it in the first place. Now it indeed does throw the error I've shown.

Is there a recommended way to uninstall my previous `hypopg` installation?

**Comment by rjuju** [comment]
There's an **uninstall** makefile rule, but I don't know if it's going to work given the errors you've shown.  That's the recommended way to uninstall it.  Otherwise you can remove the hypopg.so, hypopg.control and hypopg--*.sql found in your postgres installation tree.
