### ISSUE TITLE
Promote 2.0 release out of beta

### ISSUE THREAD

**Issue by tedyu** [HypoPG/hypopg#68]
Is there any known issue which prevents 2.0 release to come out of beta ?

REL1_STABLE branch had newer commits compared to master branch.
Does this mean REL1_STABLE branch would be the active branch going forward ?

**Comment by rjuju** [comment]
Yes, unfortunately the partition expansion code changed somewhere during the pg12 development, and it's not possible anymore to create hypothetical partitions.  There were some discussions upstream to add some new hook for that, as another project could have also used it, but nothing happened.

So for now, all the new code in v2 cannot compile anymore :(

**Comment by tedyu** [comment]
Looks like the commit in master branch which caused the compilation issue should be reverted.

This would revive the master branch.

**Comment by rjuju** [comment]
Note that there are a lot of commits that were done for that.  But the current development branch is REL1_STABLE, not master.  That's also the default branch you get when cloning the repo or on the github interface, so I don't think there's any problem here.
