### ISSUE TITLE
Hypothetical hash index may have different scan types in Explain output

### ISSUE THREAD

**Issue by tedyu** [HypoPG/hypopg#71]
Hypothetical hash index shows up as Index Scan in Explain output (where clause of the form `val > 'abc'`).

However, if the hash index is created in Postgres, the actual scan type may be range scan.

**Comment by rjuju** [comment]
Hi,

hash indexes only support plain equality operator, so I'm not sure how you could get a hash index scan with such a predicate.  Could you show a full reproducer?

**Comment by tedyu** [comment]
```create table hypo (id int, val text);
select * from hypopg_create_index('create index on hypo (val hash);');
explain select * from hypo where val > 'abc';
```

**Comment by tedyu** [comment]
https://dbfiddle.uk/?rdbms=postgres_13&fiddle=7b7bd2d590bdee020a3f3b5b533e107b

**Comment by rjuju** [comment]
For the archive's sake, here's the script and the output:

```sql
create table hypo(val text);
create index on hypo using hash(val);
explain select * from hypo where val > 'a';

QUERY PLAN
--
Seq Scan on hypo  (cost=0.00..27.00 rows=453 width=32)
Filter: (val > 'a'::text)
```

How is that behavior any different with a hypothetical version of the same index?  As I said hash AM doesn't support anything apart from the `=` operator, and that's not something hypopg could change even if it wanted to.

**Comment by tedyu** [comment]
Without the real hash index:
```
select * from hypopg_create_index('create index on hypo using hash (val)');
```
`explain select * from hypo where val > '5'` shows `Index Scan`

**Comment by rjuju** [comment]
No it doesn't:

```
rjuju=# select * from hypopg_create_index('create index on hypo using hash (val)');
 indexrelid |      indexname
------------+----------------------
      13799 | <13799>hash_hypo_val
(1 row)

rjuju=# explain select * from hypo where val > '5' ;
                       QUERY PLAN
--------------------------------------------------------
 Seq Scan on hypo  (cost=0.00..27.00 rows=453 width=32)
   Filter: (val > '5'::text)
(2 rows)

rjuju=# set enable_seqscan = off;
SET

rjuju=# explain select * from hypo where val > '5' ;
                                QUERY PLAN
---------------------------------------------------------------------------
 Seq Scan on hypo  (cost=10000000000.00..10000000027.00 rows=453 width=32)
   Filter: (val > '5'::text)
(2 rows)
```

Are you doing your tests on a modified version of postgres?  If yes, there's no guarantee of any extension working as expected unless you adapt it for your own modifications.

**Comment by tedyu** [comment]
In PG, the exclusion of index scan when the column in the filter clause is part of the hash key needs to know index->nhashcolumns.

It seems hypopg doesn't maintain index->nhashcolumns.

What mechanism does hypopg use in this case to achieve the same result ?

Thanks

**Comment by rjuju** [comment]
There's no such thing as "nhashcolumns" in postgres.  Once again I think that you're referring to something that is not vanilla postgres, and I don't see how hypopg could be compatible with some unreferenced fork.

**Comment by rjuju** [comment]
I don't understand your question.  By definition a hypothetical index doesn't exist, so there's no index relation.

**Comment by tedyu** [comment]
In `hypo_index_store_parsetree`, is it possible to access the `IndexOptInfo` which is composed by `hypo_injectHypotheticalIndex` ?

Thanks
