### ISSUE TITLE
Packages?

### ISSUE THREAD

**Issue by jfinzel** [HypoPG/hypopg#8]
For those interested in safely installing and maintaining this in a production environment, will this ever be packaged?

**Comment by rjuju** [comment]
Hi,

packages are already available for RHEL/Centos, on https://yum.postgresql.org/.  I don't think there are packages for Debian yet, but this can be fixed if needed.

**Comment by rjuju** [comment]
@jfinzel good news, v1.1.1 is out and packages are available: http://apt.postgresql.org/pub/repos/apt/pool/main/h/hypopg/

You can check https://wiki.postgresql.org/wiki/Apt is you need details on how to setup the PGDG community repository.
