### ISSUE TITLE
hypothetical partial indexes with quoting

### ISSUE THREAD

**Issue by mbanck-cd** [HypoPG/hypopg#88]
It is not clear to me whether this is supported at all, but in case it is, how would one tell hypopg to create a partial index where the condition has some string in it that I need to quote? Like 

```
SELECT hypopg_create_index('CREATE INDEX ON customer_data(creation_date) WHERE ((category = 'FOO'))');` 
ERROR:  syntax error at or near "FOO"
ROW 1: ...N customer_data(creation_date) WHERE ((category = 'FOO'))');
                                                             ^
```

**Comment by rjuju** [comment]
Hi,

This is supported.  The problem here is just your SQL syntax, as you're using a quotes inside a quoted literal.  I would recommend using dollar quoting to make it easier, e.g.:

```sql
SELECT hypopg_create_index($$CREATE INDEX ON customer_data(creation_date) WHERE ((category = 'FOO'))$$);` 
```

**Comment by mbanck-ntap** [comment]
Ah thanks - I guess that is a general thing not particular to hypopg, but it might be nice to mention that in the README

**Comment by rjuju** [comment]
Agreed, maybe the dollar quoting feature is not that well known.  I will take care of that shortly!

**Comment by rjuju** [comment]
This is now done.  Thanks a lot!
