### ISSUE TITLE
any plans for windows?

### ISSUE THREAD

**Issue by liyunMS** [HypoPG/hypopg#9]
do we have any plans to support window in the near future?

Thanks!

**Comment by rjuju** [comment]
Hi,

As far as I know the code should be supported on windows.  Do you encounter any issue?

**Comment by liyunMS** [comment]
Not yet. I just did not find any instruction on how to install this extension on windows. Can you give me some guidance on that?

Thanks!

**Comment by rjuju** [comment]
The most difficult part is probably to compile the extension, everything else will work the same.  I don't use windows myself, so I can't really help you on the compiling part.  You can check [this documentation](https://wiki.postgresql.org/wiki/Building_and_Installing_PostgreSQL_Extension_Modules#Windows_with_Microsoft_Visual_Studio) which should help you compile extensions on windows.

**Comment by marmiskeje** [comment]
@liyunMS, did you succeeded? Can you give me some guidance?  Thank you.

**Comment by kmosolov** [comment]
@marmiskeje you can try this: https://github.com/kmosolov/hypopg/tree/win32
There are hardcoded paths to Postres libs in vcxproj file, you should check and fix them.

**Comment by rjuju** [comment]
@kmosolov oh, thanks for working on windows compatibility!

Is there some way to ease this work by adding specific code in the main tree?  I looked at your modifications and think I could at least add the __declspec(dllexport) options (though using extern PGDLLEXPORT).  Anything else would be worthwhile ?

**Comment by babalubas090** [comment]
@marmiskeje you can try this: [https://github.com/babalubas090/hypopg-windows](https://github.com/babalubas090/hypopg-windows)
Just insert these files in your PostgreSQL directory. 
They are organized in subdirectories just like your PostgreSQL installation.

**Comment by Godwottery** [comment]
I wanted to run HypoPG on Windows. I took the changes from @kmosolov and applied them to 2.0.0beat. 
Necessary changes: 
 * Add PGDLLEXPORT to some functions.
 * Some conditional compilation as MSVC doesnt like INT32_MAX
 * Some explicit type-cast to silence compiler warnings.

**Comment by marmiskeje** [comment]
> 
> 
> @marmiskeje you can try this: https://github.com/kmosolov/hypopg/tree/win32
> There are hardcoded paths to PostgreSQL libs in vcxproj file, you should check and fix them.

Thanks. What version of visual c++ redistributable packages do I need?
I am getting this error:
ERROR: could not load library "C:/Program Files/PostgreSQL/11/lib/hypopg.dll": The specified procedure could not be found. SQL state: XX000

Windows server 2019
Posgtresql 11

Thank you.

**Comment by marmiskeje** [comment]
Never mind, I build it by myself in upgraded bubalubas´ project (upgraded for Visual Studio 2017). Kmosolov´s library didn´t worked for me.
Thank you, guys.

**Comment by rjuju** [comment]
Thanks for sharing an update!

**Comment by anupkumarmishra** [comment]
Getting this error for Postgres 12 installation could not load library "C:/Program Files/PostgreSQL/12/lib/hypopg.dll": The specified procedure could not be found.  I took the link shared by  @babalubas090 . @marmiskeje  can you please help as you had same issue.

**Comment by anupkumarmishra** [comment]
@Godwottery  Can you please help ?

**Comment by sfkeller** [comment]
FYI: See also issue #50 .

**Comment by rjuju** [comment]
I spent some time setting up a build environment on Windows.  As far as I can see there was one problem which prevented compilation with msvc, and I just pushed a fix for that.

I'm now working on providing zip archives / installers.  If anyone is interested in Windows packages, I'm interested in feedback with the packages I just generated for the current HEAD, which is currently version 1.3.2 but the "real" version 1.3.2 will likely have other changes, so that should be kept in mind.

[hypopg-1.3.2-pg10-x64.zip](https://github.com/HypoPG/hypopg/files/6988079/hypopg-1.3.2-pg10-x64.zip)
[hypopg-1.3.2-pg11-x64.zip](https://github.com/HypoPG/hypopg/files/6988080/hypopg-1.3.2-pg11-x64.zip)
[hypopg-1.3.2-pg12-x64.zip](https://github.com/HypoPG/hypopg/files/6988081/hypopg-1.3.2-pg12-x64.zip)
[hypopg-1.3.2-pg13-x64.zip](https://github.com/HypoPG/hypopg/files/6988082/hypopg-1.3.2-pg13-x64.zip)

**Comment by d1g1talpump** [comment]
> 

is there a possible windows build of hypopg for pg14 in the works?

**Comment by rjuju** [comment]
@d1g1talpump I just uploaded installers for pg versions 9.6 to 15 for the latest versions at https://github.com/HypoPG/hypopg/releases/tag/1.4.0

Let me know if that's working as expected.

**Comment by d1g1talpump** [comment]
> @d1g1talpump I just uploaded installers for pg versions 9.6 to 15 for the latest versions at https://github.com/HypoPG/hypopg/releases/tag/1.4.0
> 
> Let me know if that's working as expected.

brilliant, seems to be working as expected. Thanks so much for the lightening response

**Comment by rjuju** [comment]
Excellent news, thanks a lot for the feedback!

I will keep uploading the windows installer for the next releases then!  Feel free to open an issue if I forget to do so at some point.

**Comment by Joan68** [comment]
> @d1g1talpump I just uploaded installers for pg versions 9.6 to 15 for the latest versions at https://github.com/HypoPG/hypopg/releases/tag/1.4.0
> 
> Let me know if that's working as expected.

Just tried it for pg14 and seems to work, thanks a lot !
